CREATE TABLE CATEGORIE_DOCUMENTS(
    NO_CATEGORIE NUMERIC(5,0),
    LIBELLE_F VARCHAR2(50) NOT NULL,
    LIBELLE_N VARCHAR(50) NOT NULL,
    LIBELLE_D VARCHAR(50),
    LIBELLE_X VARCHAR(50),
    CONSTRAINT CAT_DOC_PK PRIMARY KEY (NO_CATEGORIE)
);

CREATE TABLE DOCUMENT(
   NO_DOCUMENT NUMERIC(5,0),
   LIBELLE_F VARCHAR2(100) NOT NULL,
   LIBELLE_N VARCHAR(100) NOT NULL,
   LIBELLE_D VARCHAR(100),
   LIBELLE_X VARCHAR(100),
   NO_CATEGORIE NUMERIC(5,0),
   CONSTRAINT DOC_PK PRIMARY KEY (NO_DOCUMENT),
   CONSTRAINT CAT_DOC_FK FOREIGN KEY (NO_CATEGORIE) REFERENCES CATEGORIE_DOCUMENTS(NO_CATEGORIE)
);